### ISSUE TITLE
Reservar um espaço para eventos

### ISSUE THREAD

**Issue by HeitorG** [cienciahacker/Index#19]
Acredito que seria super válido reservar algum espaço no repositorio para colocar eventos que tem como assunto principal ou não, segurança da informação, ou algo do tipo, um bom exemplo é o RoadSec.

**Comment by fnk0c** [comment]
Por incrível que pareça, já estamos trabalhando nisto. Porém o mesmo estará disponível no site, ao invés do github

**Comment by HeitorG** [comment]
Acho que seria válido que ele também esteja no github :smile:

**Comment by methz** [comment]
Maybe.

**Comment by fnk0c** [comment]
@HeitorG , vou ver com o resto da equipe.

**Comment by 54l0m0n** [comment]
Eventos serão feitos no site, que será integrado como agenda. Porém esta em desenvolvimento.
