### ISSUE TITLE
Links quebrados

### ISSUE THREAD

**Issue by asfelix** [cienciahacker/Index#20]
Os itens:
- [IRC Ciência Hacker](http://cienciahacker.com.br/irc/)
- [Hash Finder](http://cienciahacker.com.br/tools/hash.php)
- [Seu IP](http://cienciahacker.com.br/tools/ip.php)

da seção "Use", estão todos apresentando erro 404

**Comment by methz** [comment]
Olá, Alexsandro, obrigado pelo feedback! 
Estamos em manutenção e as ferramentas estarão prontas em breve.
Fique de olho e obrigado.

**Comment by fnk0c** [comment]
@asfelix , de fatos as ferramentas não haviam sido upadas no servidor ainda, e nem seus links haviam sido atualizados.
Commit https://github.com/cienciahacker/Index/commit/b2ec3bdf3e56888f1c5c927fe1df996f6884ded2 resolveu este problema, porém o IRC ainda se encontra em manutenção.

Obrigado por abrir este issue
